NumPy is a fundamental package for scientific computing in Python. It provides support for large, multi-dimensional arrays and matrices, as well as a wide range of mathematical functions to operate on these arrays.

1. Installation:
You can install NumPy using the following command:

In [1]:
!pip install numpy

2. Creating Arrays

In [5]:
import numpy as np

# Creating a 1d array
arr1 = np.array([1,2,3,4,5])
print("Creating a 1d array")
print(arr1)

#creating 2d array
arr2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print("Creating a 2d array")
print(arr2)

Creating a 1d array
[1 2 3 4 5]
Creating a 2d array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


5. Basic Operations

In [21]:
#Element-wise operations

result = arr1 + 2
result = arr1 * 3
result = arr1 + arr2

# array manupilation 
reshaped = arr2.reshape(2,5)
print(reshaped)
transposed = arr2.T
transposed


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

4. Indexing and Slicing and conditional rendering:

In [44]:
arr1[2] # Accessing an element

2d_subarr = arr2[1, 0:] # slicing Subarray
            arr2[1,::]
    
1d_subarr = arr1[0:5:2]

#conditional rendering
filtered = arr1[arr1 > 2]

array([3, 4, 5])

5 Maths Functions:

In [51]:
mean = np.mean(arr1)
std_dev = np.std(arr2)
max_val = np.max(arr1)
max_val 

5

array([ 6,  7,  8,  9, 10])